### PR TITLE
Notebook tests

### PR DESCRIPTION
**Pull request by javdrher**
Added tests for running the notebooks, lets see how long they run on travis.

### CODE REVIEW

**Comment by icouckuy** [comment]
Runs fine on my laptop. Timings:
/home/icouckuy/projecten/GPflowOpt/testing/../doc/source/notebooks/new_acquisition.ipynb took 118.921 seconds.
/home/icouckuy/projecten/GPflowOpt/testing/../doc/source/notebooks/hyperopt.ipynb took 383.309 seconds.
/home/icouckuy/projecten/GPflowOpt/testing/../doc/source/notebooks/constrained_bo.ipynb took 232.984 seconds.
/home/icouckuy/projecten/GPflowOpt/testing/../doc/source/notebooks/structure.ipynb took 62.8342 seconds.

With the upcoming notebooks I guess it is possible to exceed the timeout of Travis?

**Comment by javdrher** [comment]
The reason this fails on travis is because I do not install texlive, and so it fails on generating TeX labels. Installing texlive each build will be a bit time consuming so we'd have to get rid of those labels

**Comment by javdrher** [comment]
Not to be merged until I either remove the hyperopt notebook or get it stable

**Comment by icouckuy** [comment]
I fixed a bug in the structure notebook. Two notebooks are not reliable atm:
- hyperopt: doesnt find always an optimum for the sm kernel I think.

Could using MCMCAcquisition help here?

- firststeps: model training fails for 5 restarts in a row.

**Comment by javdrher** [comment]
The mystery bug is still there, I can't reproduce it locally

**Pull request merged**
