### PR TITLE
GPflow 1.0

### PR DESCRIPTION
**Pull request by javdrher**
Following up on #86 , development of a 1.0 compatible GPflowOpt version. This is far from done, the biggest difficulty (`Acquisition`) is still ahead unfortunately. 

At the same time lots of tests are affected: I'm reworking them to use some of the cool pytest features. When this work is over, I hope to do another PR to improve testing further (split out computationally demanding tests to system, use mock to test things which now trigger BO runs and model optimizations)

### CODE REVIEW

**Comment by javdrher** [comment]
Update: working on the Acquisition class. I think most cases can be covered now, only MCMC might become tricky. Overall there is quite some progress.

**Comment by javdrher** [comment]
@awav in `gpflowopt/misc.py` I added a function which I believe implements the `model.randomize()` behavior of GPflow 0.4.0. I noticed that the `Prior.sample()` interface isn't consistent in GPflow right now:
```python
>>> gpflow.priors.Uniform().sample(shape=())
0.8722288601917351
>>> gpflow.priors.Uniform().sample(shape=(5,))
array([ 0.76688813,  0.74866882,  0.32043899,  0.96846279,  0.74190276])
>>> gpflow.priors.Gaussian(0,1).sample(shape=())
array([-1.68982972])
>>> gpflow.priors.Gaussian(0,1).sample(shape=(5,))
array([-0.02267741, -2.12480833,  0.38060906,  1.48536884,  0.13014313])
>>> gpflow.priors.Beta(1,1).sample(shape=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/javdrher/.virtualenvs/gpflowopt-nextgen/lib/python3.6/site-packages/gpflow/priors.py", line 105, in sample
    return np.random.beta(self.a, self.b, size=shape)
  File "mtrand.pyx", line 1714, in mtrand.RandomState.beta
  File "mtrand.pyx", line 267, in mtrand.cont2_array
ValueError: size is not compatible with inputs
>>> gpflow.priors.Beta(1,1).sample(shape=(1,))
array([ 0.06183377])
gpflow.priors.Laplace(1,1).sample(shape=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/javdrher/.virtualenvs/gpflowopt-nextgen/lib/python3.6/site-packages/gpflow/priors.py", line 89, in sample
    return np.random.laplace(self.mu, self.sigma, size=shape)
  File "mtrand.pyx", line 3075, in mtrand.RandomState.laplace
  File "mtrand.pyx", line 267, in mtrand.cont2_array
ValueError: size is not compatible with inputs
>>> gpflow.priors.Gamma(1,1).sample(shape=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/javdrher/.virtualenvs/gpflowopt-nextgen/lib/python3.6/site-packages/gpflow/priors.py", line 73, in sample
    return np.random.gamma(self.shape, self.scale, size=shape)
  File "mtrand.pyx", line 1989, in mtrand.RandomState.gamma
  File "mtrand.pyx", line 267, in mtrand.cont2_array
ValueError: size is not compatible with inputs
``` 
Its quite common for `gpflow.Parameter` to have `()` as shape, but the `np.random` responds quite shaky to this input.

**Comment by javdrher** [comment]
Regarding MCMC: GPflow models can no longer be copied. This means our implementation can not be fixed and we'll have to pull the MCMC step out of the TF graph and external to `acquisition.evaluate`. It's going to make it a little bit less useful as the `MCMCAcquisition` made it very easy to drag the MCMC along when not using `BayesianOptimizer`.

**Comment by javdrher** [comment]
Ok, most of it is done. Overview of the changes for users:

(1) I had a significant performance problem due to lots of calls to `gpflow.misc.initialiaze_variables`. Many of them were caused by our model optimization restarting. Although still available, I disabled it by default. We should verify if this raises the number of modeling failures. @awav , is it somehow possible to suspend all initializations caused by calls to `assign`, and do them only at the end? 
(2) MCMC is performed outside of the graph now because copying models has become impossible, due to the same reason as the previous point, it became slow.
(3) VGP support is broken, fix proposed in GPflow/GPflow#617 
(4) Lazy recompilation was removed in GPflow, and is the responsibility of the user now. Anticipating on this is difficult for GPflowOpt (unless we just clear/compile by default), so if a clear/compile is needed it should be done through our callback system. In the default callback, I added an implementation for VGP models.

In the background, I changed the test suite to use pytest fixtures which makes it extremely clean

Left to do:
- some cleanup (myself)
- documentation update (@icouckuy ?)
- checking the notebooks (@nknudde ?)
- pep8 check

**Comment by rpinsler** [comment]
Any updates on this?

**Comment by javdrher** [comment]
Unfortunately I had no time to solve the remaining issues. I might have some time to look into this again next week.

**Comment by javdrher** [comment]
Good news, this branch is still quite compatible with GPflow 1.2, looking into the performance issues we had: hopefully I can get them resolved

**Comment by javdrher** [comment]
There are a small number of things I should solve (this odd failing test for instance), then I propose to merge this. We might need a couple of PRs after this to clean up and solve some loose ends, then we can release this as 0.2

**Comment by Joshuaalbert** [comment]
Re: `GPflow models can no longer be copied. `. Is it not possible to to use save and restore? I.e. @awav 's reply in https://github.com/GPflow/GPflow/issues/753.

**Comment by Joshuaalbert** [comment]
I'm getting
from 
``` python
from gpflowopt.design import LatinHyperCube
from gpflowopt.acquisition import ExpectedImprovement
from gpflowopt import optim, BayesianOptimizer
domain = ContinuousParameter('a',0,1)
X = ...
Y = ...
m = GPR(X, Y, kern=Matern52(domain.size, ARD=False))
ei = ExpectedImprovement(m)
opt = optim.StagedOptimizer([optim.SciPyOptimizer(domain)])
optimizer = BayesianOptimizer(domain, ei, optimizer=opt)
def objective(x):
    # x is a scalar ContinuousParameter in [0,1] 
    return x
optimizer.optimize(objective, n_iter=n_iter)
```

``` bash
  File "/home/albert/miniconda3/envs/tectf/lib/python3.6/site-packages/gpflowopt-0.2.0-py3.6.egg/gpflowopt/bo.py", line 313, in optimize
  File "/home/albert/miniconda3/envs/tectf/lib/python3.6/site-packages/gpflowopt-0.2.0-py3.6.egg/gpflowopt/optim.py", line 78, in optimize
  File "/home/albert/miniconda3/envs/tectf/lib/python3.6/site-packages/gpflowopt-0.2.0-py3.6.egg/gpflowopt/bo.py", line 260, in _optimize
  File "/home/albert/miniconda3/envs/tectf/lib/python3.6/site-packages/gpflowopt-0.2.0-py3.6.egg/gpflowopt/optim.py", line 268, in optimize
UnboundLocalError: local variable 'result' referenced before assignment
```

https://github.com/GPflow/GPflowOpt/blob/gpflow-1.0-v3/gpflowopt/optim.py#L268

**Comment by icouckuy** [comment]
@Joshuaalbert Did you check if you can copy the acquisition object properly? That comment might have been before GPFlow's new save/ restore functionality. If it does not work yet, it might be possible to hook the save/restore into gpflowopt somehow.

StagedOptimizer takes at least a list of 2 optimizers. I have added an assert in the constructor for now. Alternatively, we can get it to work with a list of 1 too. In fact, that might be a better solution.

**Comment by javdrher** [comment]
@Joshuaalbert 
That comment was indeed made before the model saving functionality. I'll check in more detail how the mechanism works and check if we can use it to recover the original MCMC functionality. We will do this in a later PR though. 

Regarding the optimizer issue, you can simply do
```python
opt = optim.SciPyOptimizer(domain)
```

**Comment by jklaise** [comment]
Any updates? What is left to be done?

**Comment by icouckuy** [comment]
The branch is more or less in working order, depending on changes in the meantime on GPFlow's side. It does need a lot more testing and we need to rewrite some code a bit more (like using the logging framework of TF/GPFlow).

However we decided this branch should be merged first, as it works, and make those changes as new PRs. For this branch to merge the tests should be fixed first.

@javdrher correct me if I'm wrong

**Comment by javdrher** [comment]
There's a small number of tests failing left, so functionally all is fine. There is however a serious issue: GPflowOpt often changes values of dataholders and parameters. In the past, this was no problem as those values were all inserted into the graph through a `feed_dict`, but starting from GPflow 1.0 this requires the use of `parameter.assign` which is an inherently slow operation. Most of our notebooks are running terribly slow (order of 15 minutes to select 25 points on a 2D problem) and I'm afraid there is not a lot we can do to remedy that. 

Around that time I had a chat with @awav regarding their plans for GPflow 2.0 and it seemed to be a good option to discontinue work on this branch and focus on that instead. Unfortunately I haven't heard a lot back from that so far (there is a branch in the GPflow repository but some questions regarding data management are still open).  As soon as that becomes clear, we can plan again and make a compatible version. 

For GPflow 1.0 compatibility, I still don't see a way out. _We could, theoretically stop reusing the same model over and over again, and create new ones each iteration. This is something we have actually done in a couple of projects, but this is also very slow unfortunately._

**Comment by javdrher** [comment]
I'm closing this. Conclusion is to focus on GPflow 2.0 instead.

**Pull request closed without merging**
